### ISSUE TITLE
Not compatible with PHP 8.1

### ISSUE THREAD

**Issue by estento** [SetBased/php-audit#66]
Hi,
On Ubuntu 22.04, PHP 8.1, running the audit script produces a fatal error. If someone can suggest a fix, I would be grateful.

```
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught SetBased\Exception\ErrorException: Return type of Noodlehaus\AbstractConfig::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/cp/vendor/hassankhan/config/src/AbstractConfig.php:184
Stack trace:
#0 /var/www/cp/vendor/hassankhan/config/src/AbstractConfig.php(17): SetBased\ErrorHandler\ErrorHandler->handleError()
#1 /var/www/cp/vendor/composer/ClassLoader.php(571): include('...')
#2 /var/www/cp/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /var/www/cp/vendor/hassankhan/config/src/Config.php(22): Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/cp/vendor/composer/ClassLoader.php(571): include('...')
#5 /var/www/cp/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#6 /var/www/cp/vendor/setbased/php-audit/src/Command/BaseCommand.php(61): Composer\Autoload\ClassLoader->loadClass()
#7 /var/www/cp/vendor/setbased/php-audit/src/Command/AuditCommand.php(42): SetBased\Audit\Command\BaseCommand->readConfigFile()
#8 /var/www/cp/vendor/symfony/console/Command/Command.php(298): SetBased\Audit\Command\AuditCommand->execute()
#9 /var/www/cp/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#10 /var/www/cp/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/cp/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#12 /var/www/cp/vendor/setbased/php-audit/bin/audit(28): Symfony\Component\Console\Application->run()
#13 /var/www/cp/vendor/bin/audit(117): include('...')
#14 {main} in /var/www/cp/vendor/hassankhan/config/src/AbstractConfig.php on line 17

```

**Comment by prwater** [comment]
This issues has been solved in release 1.8.0.
